version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    restart: always
    volumes:
      - persis:/app/data

volumes:
  persis:
